### PR TITLE
Create ZoweVenues

### PR DESCRIPTION
**Pull request by RASakach**
Signed-off-by: Rose Sakach <Rose.Sakach@broadcom.com>

### CODE REVIEW

**Comment by RASakach** [comment]
Create folder to house Conference / Webinar Information

**Comment by RASakach** [comment]
@Joe-Winchester  - does it make sense to create a folder for our conference spreadsheet?  I'm not sure I've done this correctly.  :-(

**Comment by Joe-Winchester** [comment]
@RASakach - I don't see any files in this commit.  Did you want to attach the spreadsheet to the PR ?  Slack me if you want and maybe we can webex/zoom and get everything ticketyboo

**Comment by jmertic** [comment]
Hey - seeing this and wondering if this is intended to be different than what @Maemalynn tracks. Can you elaborate?

**Comment by RASakach** [comment]
Hi @jmertic - we are using this spreadsheet to track 2021 Conferences where we expect / would like Zowe sessions represented.  @Maemalynn is aware of this and has created a google sheet for us.  I wanted to be sure the Community had access to view it so I wanted to post it here.  Does this clarify?

**Comment by jmertic** [comment]
I think so - so is the same Google Sheet or a different one you are posting here? If it's a manual copy - that's probably some unneeded work on you and we should figure out how to eliminate that.

**Comment by RASakach** [comment]
Was hoping to post the link here so that we are all looking at the same - and only - Google sheet.

**Comment by jmertic** [comment]
Awesome - that works perfect!

**Pull request closed without merging**
