### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by jmertic**
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by Tbr00ksy** [comment]
Should this belong in the ZLC repo with the other process docs?

**Comment by jmertic** [comment]
TBH - I think both zlc and community could be folded into one repo.

**Comment by Tbr00ksy** [comment]
How (or do we even need to) differentiate read/write access between the ZLC and Community repos?

**Comment by jmertic** [comment]
Not sure if we need to. Especially if everything comes in via PR.

**Pull request closed without merging**
