### PR TITLE
Translate COMMITTERS.md to a CSV file for easier parsing

### PR DESCRIPTION
**Pull request by jmertic**
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by jmertic** [comment]
@armstro Could we add this to the next ZLC agenda?

**Comment by armstro** [comment]
Yes @jmertic we can add to the agenda - I have a set a questions around when and how this file gets created. (How is this process automated and what repos are included?) We had a recent request to confirm one of the IBM committers and because they were relatively new to the team, were not seen in the committer file. Also, the individual was on the CI/CD (aka Systems Team) squad and his work is more in Jenkins and related repos - @Joe-Winchester and Murali have been helping me track this down so raising this pull request is timely - plus we should have voting for TSC coming up.

**Comment by Joe-Winchester** [comment]
This looks great !  It's a new file so I've merged it into master to close the PR - and going forward we can start a discussion in an issue for the ZLC about how this file gets maintained and how it relates to who actually has commit rights to which repo.  Cheers !

**Comment by armstro** [comment]
@jmertic Understand you had something come up that prevented you from attending ZLC today ....I was unclear what the "ask" was for this file but that did not prevent us from discussing it anyway .....{8-) .....are you wanting approval? I don't think we got agreement on that today. 

- @1000TurquoisePogs Sean also pointed out that his attempt to put pointers in the original file to the committers for the repos he deals with was apparently not taken into account in the CSV - some additional work is likely needed to figure out how to handle 

- My understanding is this was a manual process to create - this triggered some discussion on the need to automate and keep current (see above - there was a recent situation where an individual was possibly denied a IBM contributor badge because they are relatively new to the team but has been an active committer on CI/CD team) 

We do think this needs to be updated fairly soon as we will need voting on TSC ......

So please clarify the ask and be aware we likely need some work to handle Sean's concern. (Automating will be a future to-do.)

**Comment by jmertic** [comment]
Hi! So ask wise - nothing in particular other than an ask if we can move from the .md format to this .csv format. 

In terms of keeping up to date, we do need each of the squads to maintain it's committer list. I know @1000TurquoisePogs tended to have a pointer to the ACLs which is what he mentioned.

I guess in the end of the day my goal is to have a parseable list of Zowe Committers for both voting purposes, and awarding badges ( which many got some over the last week ). Happy to discuss the specifics of squads managing this.

**Pull request merged**
