### PR TITLE
Add information about the different sections

### PR DESCRIPTION
**Pull request by balhar-jakub**
Add information about the different sections

### CODE REVIEW

**Review by Joe-Winchester — APPROVED** [review]
This looks great !   Many thanks @balhar-jakub  for editing the guidelines.
When this goes live an editor of medium.com/zowe should then update the feature pages on medium.com/zowe.  I'm happy to this, or else @samanthasusu could also, so we'll watch for when this PR is merged.
Thank you

**Comment by balhar-jakub** [comment]
Unless there are concerns, I intend to merge this PR next Wednesday e.g. Feb 7

**Comment by samanthasusu** [comment]
Screenshot 2024-02-02 at 17 59 46
Good to see the great new guidelines! Please see the to-be on medium.com/zowe once the pull request merged. Thanks

**Comment by samanthasusu** [comment]
@balhar-jakub Thank you Jakub for doing this! The changes go live now https://medium.com/zowe

**Pull request merged**
