### PR TITLE
Add CLI Squad Focus

### PR DESCRIPTION
**Pull request by MikeBauerCA**
Signed-off-by: MikeBauerCA <35504792+MikeBauerCA@users.noreply.github.com>

### CODE REVIEW

**Comment by MikeBauerCA** [comment]
@zFernand0 @solsu01 @MarkAckert please review/merge quickly before this becomes out of date... perhaps we should collaborate outside GitHub on this initiative (e.g. Google Drive, Box, etc.)

**Comment by zFernand0** [comment]
> please review/merge quickly before this becomes out of date... perhaps we should collaborate outside GitHub on this initiative (e.g. Google Drive, Box, etc.)

@MikeBauerCA, people can still contribute in the Box PPT.
https://ibm.box.com/s/rczaexjsoywxky3dge4jd45o872y6uve (Similar to how the OnBoarding squad did it.

**Comment by zFernand0** [comment]
FYI, the Notes for Feature 1 for the CLI was copied from Feature 1 of the API ML.
Was that expected?

**Comment by MikeBauerCA** [comment]
Thanks @zFernand0, I removed the notes

**Pull request merged**
